server:
  port: 9093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productconsumerdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        generate_statistics: true
      application:
        name: PRODUCT-CONSUMER-SERVICE
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: product.exchange
    queue: product.queue
    routingkey: product.routingkey